apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.db.labels.app }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.db.selectorLabels.app }}
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.port }}
      protocol: TCP