apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  postgres-user: {{ .Values.db.secret.user | b64enc | quote }}
  postgres-password: {{ .Values.db.secret.password | b64enc | quote }}